name: Changeset
on:
  push:
    branches:
      - main

concurrency:
  group: changeset
  cancel-in-progress: true

jobs:
  changeset:
    name: Changeset
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      pull-requests: write
      issues: read
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: pnpm
        uses: pnpm/action-setup@v4
      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: install
        run: pnpm install
      - name: build
        run: pnpm build --filter='./packages/*'
      - name: changesets
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
